name: Hello World

# Events

on: 
  push:
    branches: 
     - main
  pull_quest:
    branches:
      - main
  
  
  workflow_dispatch:


  # Workfkow / Jobs

  jobs:
    hello:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Hello
          run: echo "Hello World"
          shell: bash
