name: Hello World

#  Events

on:
  push:
    branches:
      - main

   pull_request:
        branches:
          - main

          workflow_dispatch:


          # Workflow / Jobs

          jobs:
            hello:
              runs-on:  ubuntu-latest
              steps:
                - uses: actions/checkout@v4
                - name: Hello
                  run: echo  "Hello World"
                  shell: bash

                   jobs2:
            hello:
              runs-on:  ubuntu-latest
              steps:
                - uses: actions/checkout@v4
                - name: Hello2
                  run: echo  "Hello World2"
                  shell: bash
